# Stage 1 : Builder

FROM node:20-alpine AS builder

WORKDIR /app

COPY . .

RUN npm ci && \
    npx prisma generate

RUN npm run build

COPY init_nest.sh ./

RUN sed -i 's/\r$//' init_nest.sh && chmod +x init_nest.sh

EXPOSE 3000

CMD ["/app/init_nest.sh"]