services: 
  nats:
    image: nats:alpine
    restart: always
    ports:
      - "4222:4222"
      - "8222:8222"
    healthcheck:
      test: wget http://localhost:8222/healthz -q -S -O -
      start_period: 3s
      retries: 3
      timeout: 3s
      interval: 14s
    networks:
      - microservices-network-dev

  mysql:
    image: mysql
    container_name: db_projet
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: gestion_file
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - microservices-network-dev
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 40s

  phpmyadmin:
    image: phpmyadmin
    depends_on:
      mysql:
        condition: service_healthy
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    networks:
      - microservices-network-dev

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "bash", "-c", "echo > /dev/tcp/localhost/27017"]      
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s
    volumes:
      - mongodb-data:/data/db
    networks:
      - microservices-network-dev

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/notification_db?authSource=admin
      ME_CONFIG_BASICAUTH_ENABLED: true
      ME_CONFIG_BASICAUTH_USERNAME: mongoexpressuser
      ME_CONFIG_BASICAUTH_PASSWORD: mongoexpresspass
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8081"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    networks:
      - microservices-network-dev

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    networks:
      - microservices-network-dev

  gateway:
    build:
      context: ./gateway
      dockerfile: /Dockerfile
    container_name: gateway-api
    environment:
      NODE_ENV: development
      NATS_URL: nats://nats:4222
      PORT: 3000
      DATABASE_URL: mysql://root:root@mysql:3306/gestion_file
    ports:
      - "3000:3000"
      - "9229:9229" 
    volumes:
      - ./gateway/src:/app/src
      - ./gateway/prisma:/app/prisma
      - ./gateway/init-db.sh:/app/init-db.sh 
      - /app/node_modules
    depends_on:
      mysql:
        condition: service_healthy
      nats:
        condition: service_healthy
      notification-service:
        condition: service_healthy
    networks:
      - microservices-network-dev
    restart: unless-stopped

  notification-service:
    build:
      context: ./notification
      dockerfile: /Dockerfile
    container_name: notification
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - NATS_URL=nats://nats:4222
      - SPRING_DATA_MONGODB_URI=mongodb://root:example@mongo:27017/notification_db?authSource=admin
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SPRING_MAIL_HOST=smtp.gmail.com
      - SPRING_MAIL_PORT=587
      - SPRING_MAIL_USERNAME=notifications.ms.gestion@gmail.com
      - SPRING_MAIL_PASSWORD=pbps venz zjvv yccp
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH=true
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE=true
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_REQUIRED=true
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_PROTOCOLS=TLSv1.2
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_CONNECTIONTIMEOUT=5000
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_TIMEOUT=5000
      
    depends_on:
      mongo:
        condition: service_healthy
      nats:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - microservices-network-dev
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8082/actuator/health"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 40s
    restart: unless-stopped

volumes:
  mongodb-data:
  redis-data:
  db-data:
    driver: local

networks:
  microservices-network-dev:
    driver: bridge