services:
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 8090:80
    environment:
      PMA_HOST: database-projet.c3agsaymkxi0.eu-west-3.rds.amazonaws.com
      PMA_USER: nestjs_user
      PMA_PASSWORD: root_password
    networks:
      - gestion_fichier-network-dev
      - nginx-network
  backend:
    build: .
    container_name: nestjs_api
    expose:
      - "3000"
    env_file:
      - ./.env.production
    depends_on:
      - phpmyadmin
    networks:
      - gestion_fichier-network-dev
      - nginx-network
    restart: unless-stopped
  frontend:
    build:
      context: ../gestion-de-donnees_front
      dockerfile: Dockerfile
    container_name: react_app
    expose:
      - "80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - nginx-network
      - gestion_fichier-network-dev
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy-manager
    restart: always
    ports:
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
    environment:
      DISABLE_IPV6: 'true'
    networks:
      - nginx-network
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

volumes:
  db-projet-data:
    driver: local

networks:
  gestion_fichier-network-dev:
    name: gestion_fichier-network-dev
    driver: bridge
  nginx-network:
    name: nginx-network
    external: true
