FROM node:20-alpine

RUN apk add --no-cache openssl

WORKDIR /app

COPY package*.json ./
COPY prisma ./prisma

RUN npm install

RUN npx prisma generate

COPY . .

RUN chmod +x init-db.sh

RUN chmod +x init-rds.sh

EXPOSE 3000

EXPOSE 9229

CMD ["sh", "-c", "npx prisma migrate deploy && npm run start:dev"]