spring.application.name=notification
server.port=8082
api.base-url=http://localhost:3000/api/v1
 
spring.mail.host=${SPRING_MAIL_HOST:smtp.gmail.com}
spring.mail.port=${SPRING_MAIL_PORT:587}
spring.mail.username=${SPRING_MAIL_USERNAME:notifications.ms.gestion@gmail.com}
spring.mail.password=${SPRING_MAIL_PASSWORD:pbps venz zjvv yccp}
spring.mail.properties.mail.smtp.auth=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH:true}
spring.mail.properties.mail.smtp.starttls.enable=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE:true}
spring.mail.properties.mail.smtp.starttls.required=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_REQUIRED:true}
spring.mail.properties.mail.smtp.starttls.protocols=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_PROTOCOLS:TLSv1.2}
spring.mail.properties.mail.smtp.connectiontimeout=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_CONNECTIONTIMEOUT:5000}
spring.mail.properties.mail.smtp.timeout=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_TIMEOUT:5000}

spring.data.mongodb.uri=mongodb://root:example@mongo:27017/notification_db?authSource=admin

spring.data.redis.host=${REDIS_HOST:redis}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.password=  
spring.data.redis.timeout=60000
spring.data.redis.database=0

NATS_URL=nats://nats:4222

logging.level.org.springframework=DEBUG
spring.data.mongodb.auto-index-creation=true
app.firebase-configuration-file=notifications-f95c1-firebase-adminsdk-fbsvc-63514e0fa0.json