spring.application.name=notification
server.port=8082
api.base-url=http://localhost:3000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=notifications.ms.gestion@gmail.com
spring.mail.password=pbps venz zjvv yccp 
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.data.mongodb.uri=mongodb://root:example@mongo:27017/notification_db?authSource=admin

spring.data.redis.host=${REDIS_HOST:redis}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.password=  
spring.data.redis.timeout=60000
spring.data.redis.database=0

NATS_URL=nats://nats:4222

logging.level.org.springframework=DEBUG
spring.data.mongodb.auto-index-creation=true
app.firebase-configuration-file=notifications-f95c1-firebase-adminsdk-fbsvc-63514e0fa0.json