spring.application.name=notification
api.base-url=http://localhost:3000/api/v1

email=notifications.ms.gestion@gmail.com

spring.data.mongodb.uri=mongodb://root:example@mongo:27017/notification_db?authSource=admin

spring.data.redis.host=redis
spring.data.redis.port=6379
spring.data.redis.password=  
spring.data.redis.timeout=60000
spring.data.redis.database=0

NATS_URL=nats://nats:4222

logging.level.org.springframework=DEBUG
spring.data.mongodb.auto-index-creation=true
app.firebase-configuration-file=notifications-f95c1-firebase-adminsdk-fbsvc-63514e0fa0.json

spring.profiles.active=prod