export enum TypeNotification {
  SHAREFILE = 'SHAREFILE',
  REMINDER_EXPIRATION = 'REMINDER_EXPIRATION',
  JOINGROUP = 'JOINGROUP',
  ACCESSFILE = 'ACCESSFILE',
  EXPIRED_TOKEN = 'EXPIRED_TOKEN',
  CONFIRM_ACCOUNT = 'CONFIRM_ACCOUNT',
  REQUEST_FILE = 'REQUEST_FILE',
  IMPORT_FILE = 'IMPORT_FILE',
}
