export enum TypeNotification {
    SHAREFILE = "SHAREFILE", 
    REMINDER_EXPIRATION = "REMINDER_EXPIRATION", 
    JOINGROUP = "JOINGROUP", 
    ACCESSFILE = "ACCESSFILE", 
    EXPIRED_TOKEN = "EXPIRED_TOKEN"
}